// ──────────────────────────────────────────────
// Game: Map Generation Service
// ──────────────────────────────────────────────

/** Build the prompt for generating a map of the current area. */
export function buildMapGenerationPrompt(locationType: string, context: string): string {
  return [
    `Generate a map for the current area in the RPG game.`,
    ``,
    `Location type: ${locationType}`,
    `Context: ${context}`,
    ``,
    `Rules:`,
    `- For outdoor areas (overworld, city, forest, etc.): generate a "grid" type map (6x6 to 8x8)`,
    `- For indoor areas (dungeon, cave, building, etc.): generate a "node" type map`,
    `- Node maps should follow the area's physical routes: use irregular chains, branches, junctions, and occasional loops`,
    `- Avoid hub-and-spoke or star layouts where every room connects to one central node, unless the context explicitly describes a central hub`,
    `- For node maps with 6 or more rooms, distribute connections across multiple junctions; most rooms should have 1 to 3 connections`,
    `- Stagger node coordinates across the canvas instead of placing rooms at equal distances around a center point`,
    ``,
    `Grid map format:`,
    `{`,
    `  "type": "grid",`,
    `  "name": "Area Name",`,
    `  "description": "Brief area description",`,
    `  "width": 6, "height": 6,`,
    `  "cells": [{"x": 0, "y": 0, "emoji": "🌲", "label": "Dense Forest", "discovered": true, "terrain": "forest"}],`,
    `  "partyPosition": {"x": 3, "y": 3}`,
    `}`,
    ``,
    `Node map format:`,
    `{`,
    `  "type": "node",`,
    `  "name": "Dungeon Name",`,
    `  "description": "Brief dungeon description",`,
    `  "nodes": [`,
    `    {"id": "entrance", "emoji": "🚪", "label": "Entrance", "x": 48, "y": 90, "discovered": true},`,
    `    {"id": "hallway1", "emoji": "🕯️", "label": "Lower Hall", "x": 44, "y": 70, "discovered": true},`,
    `    {"id": "library", "emoji": "📚", "label": "Dusty Library", "x": 24, "y": 51, "discovered": false},`,
    `    {"id": "stairs", "emoji": "🪜", "label": "Broken Stair", "x": 65, "y": 45, "discovered": false}`,
    `  ],`,
    `  "edges": [`,
    `    {"from": "entrance", "to": "hallway1"},`,
    `    {"from": "hallway1", "to": "library"},`,
    `    {"from": "hallway1", "to": "stairs"}`,
    `  ],`,
    `  "partyPosition": "entrance"`,
    `}`,
    ``,
    `Use diverse emojis for different terrain/room types. Mark the party's starting position as discovered.`,
    `Nearby cells/nodes should also be discovered; distant ones should be undiscovered (discovered: false).`,
    ``,
    `Output ONLY the JSON map object, no other text.`,
  ].join("\n");
}
