import { index, integer, text, uniqueIndex, sqliteTable } from "drizzle-orm/sqlite-core";

export const stateAuthorityRecords = sqliteTable(
  "state_authority_records",
  {
    id: text("id").primaryKey(),
    authorityKind: text("authority_kind").notNull(),
    actorType: text("actor_type").notNull(),
    actorId: text("actor_id").notNull(),
    authorityPath: text("authority_path").notNull(),
    targetKey: text("target_key").notNull(),
    reason: text("reason").notNull(),
    issuedBy: text("issued_by").notNull(),
    authorizationKey: text("authorization_key").notNull(),
    createdAt: text("created_at").notNull(),
  },
  (table) => [uniqueIndex("idx_state_authority_records_authorization").on(table.authorizationKey)],
);

export const statePatchProposals = sqliteTable(
  "state_patch_proposals",
  {
    id: text("id").primaryKey(),
    schemaVersion: integer("schema_version").notNull(),
    targetKind: text("target_kind").notNull(),
    targetScope: text("target_scope").notNull(),
    targetId: text("target_id").notNull(),
    targetKey: text("target_key").notNull(),
    operation: text("operation").notNull(),
    patchJson: text("patch_json").notNull(),
    patchHash: text("patch_hash").notNull(),
    baseRevision: integer("base_revision").notNull(),
    evidenceKind: text("evidence_kind").notNull(),
    chatId: text("chat_id"),
    turnId: text("turn_id"),
    messageId: text("message_id"),
    swipeIndex: integer("swipe_index"),
    sourceContentHash: text("source_content_hash"),
    canonicalRevision: integer("canonical_revision"),
    authorityRecordId: text("authority_record_id"),
    authorityReason: text("authority_reason"),
    authoritySourceHash: text("authority_source_hash"),
    actorType: text("actor_type").notNull(),
    actorId: text("actor_id").notNull(),
    authorityPath: text("authority_path").notNull(),
    agentRunId: text("agent_run_id"),
    pipelineStage: text("pipeline_stage"),
    writerPriority: integer("writer_priority").notNull(),
    commitGroupId: text("commit_group_id").notNull(),
    dependencyIdsJson: text("dependency_ids_json").notNull().default("[]"),
    failureBoundary: text("failure_boundary").notNull(),
    failureMode: text("failure_mode").notNull(),
    logicalPatchSlot: text("logical_patch_slot").notNull(),
    idempotencyKey: text("idempotency_key").notNull(),
    status: text("status").notNull().default("proposed"),
    diagnosticJson: text("diagnostic_json"),
    commitId: text("commit_id"),
    createdAt: text("created_at").notNull(),
    resolvedAt: text("resolved_at"),
  },
  (table) => [
    uniqueIndex("idx_state_patch_proposals_idempotency").on(table.idempotencyKey),
    index("idx_state_patch_proposals_target_status").on(table.targetKey, table.status, table.createdAt),
    index("idx_state_patch_proposals_chat_turn_status").on(table.chatId, table.turnId, table.status),
    index("idx_state_patch_proposals_message_swipe").on(table.messageId, table.swipeIndex),
    index("idx_state_patch_proposals_agent_run").on(table.agentRunId),
  ],
);

export const stateParityVerifications = sqliteTable(
  "state_parity_verifications",
  {
    id: text("id").primaryKey(),
    proposalId: text("proposal_id"),
    adapterKind: text("adapter_kind").notNull(),
    targetKey: text("target_key").notNull(),
    legacyHash: text("legacy_hash").notNull(),
    predictedHash: text("predicted_hash").notNull(),
    matched: integer("matched", { mode: "boolean" }).notNull(),
    diagnosticJson: text("diagnostic_json"),
    createdAt: text("created_at").notNull(),
  },
  (table) => [index("idx_state_parity_target_created").on(table.targetKey, table.createdAt)],
);

export const stateTargetHeads = sqliteTable("state_target_heads", {
  targetKey: text("target_key").primaryKey(),
  targetKind: text("target_kind").notNull(),
  targetScope: text("target_scope").notNull(),
  targetId: text("target_id").notNull(),
  revision: integer("revision").notNull().default(0),
  lastCommitId: text("last_commit_id"),
  stateHash: text("state_hash").notNull().default(""),
  updatedAt: text("updated_at").notNull(),
});

export const stateCommitLedger = sqliteTable(
  "state_commit_ledger",
  {
    id: text("id").primaryKey(),
    proposalId: text("proposal_id").notNull(),
    targetKey: text("target_key").notNull(),
    targetKind: text("target_kind").notNull(),
    targetScope: text("target_scope").notNull(),
    targetId: text("target_id").notNull(),
    baseRevision: integer("base_revision").notNull(),
    resultRevision: integer("result_revision").notNull(),
    operation: text("operation").notNull(),
    patchJson: text("patch_json").notNull(),
    patchHash: text("patch_hash").notNull(),
    beforeHash: text("before_hash").notNull(),
    resultHash: text("result_hash").notNull(),
    evidenceKind: text("evidence_kind").notNull(),
    evidenceChatId: text("evidence_chat_id"),
    evidenceTurnId: text("evidence_turn_id"),
    evidenceMessageId: text("evidence_message_id"),
    evidenceSwipeIndex: integer("evidence_swipe_index"),
    evidenceContentHash: text("evidence_content_hash"),
    evidenceCanonicalRevision: integer("evidence_canonical_revision"),
    evidenceReason: text("evidence_reason"),
    evidenceSourceHash: text("evidence_source_hash"),
    actorType: text("actor_type").notNull(),
    actorId: text("actor_id").notNull(),
    authorityPath: text("authority_path").notNull(),
    authorityRecordId: text("authority_record_id"),
    batchId: text("batch_id").notNull(),
    commitOrder: integer("commit_order").notNull().default(0),
    commitGroupId: text("commit_group_id"),
    dependencyCommitIds: text("dependency_commit_ids").notNull().default("[]"),
    compensatesCommitId: text("compensates_commit_id"),
    idempotencyKey: text("idempotency_key").notNull(),
    committedAt: text("committed_at").notNull(),
  },
  (table) => [
    uniqueIndex("idx_state_commit_ledger_proposal").on(table.proposalId),
    uniqueIndex("idx_state_commit_ledger_idempotency").on(table.idempotencyKey),
  ],
);

export const relationshipSaves = sqliteTable(
  "relationship_saves",
  {
    id: text("id").primaryKey(),
    targetKey: text("target_key").notNull(),
    chatId: text("chat_id").notNull(),
    characterId: text("character_id").notNull(),
    personaId: text("persona_id").notNull(),
    schemaVersion: integer("schema_version").notNull().default(1),
    revision: integer("revision").notNull().default(0),
    state: text("state").notNull().default("{}"),
    activeTruthCount: integer("active_truth_count").notNull().default(0),
    milestoneCount: integer("milestone_count").notNull().default(0),
    lastCheckpointId: text("last_checkpoint_id"),
    projectionHash: text("projection_hash").notNull().default(""),
    sourceCommitId: text("source_commit_id"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (table) => [uniqueIndex("idx_relationship_saves_target").on(table.targetKey)],
);

export const relationshipCheckpoints = sqliteTable("relationship_checkpoints", {
  id: text("id").primaryKey(),
  relationshipSaveId: text("relationship_save_id").notNull(),
  targetKey: text("target_key").notNull(),
  schemaVersion: integer("schema_version").notNull().default(1),
  revision: integer("revision").notNull(),
  canonicalMessageCount: integer("canonical_message_count").notNull(),
  startMessageId: text("start_message_id").notNull(),
  endMessageId: text("end_message_id").notNull(),
  messageHashes: text("message_hashes").notNull().default("[]"),
  previousCheckpointId: text("previous_checkpoint_id"),
  policyVersion: text("policy_version").notNull(),
  characterTruthTokens: integer("character_truth_tokens").notNull().default(0),
  activeState: text("active_state").notNull().default("{}"),
  classifications: text("classifications").notNull().default("[]"),
  sourceCommitIds: text("source_commit_ids").notNull().default("[]"),
  status: text("status").notNull().default("valid"),
  creationReason: text("creation_reason").notNull(),
  createdAt: text("created_at").notNull(),
});
